options:
  logging: CLOUD_LOGGING_ONLY

available_secrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/OPENAI_KEY/versions/latest
      env: 'OPENAI_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_SUPABASE_KEY/versions/latest
      env: '_NEXT_PUBLIC_SUPABASE_KEY'

steps:
  # 1️⃣ Build Step
  - name: node:22
    entrypoint: bash
    args:
      - -c
      - |
        corepack enable
        pnpm install --no-frozen-lockfile
        # We must manually copy static files for the standalone build to work
        pnpm run build
        cp -r build/static build/standalone/build/static
        cp -r public build/standalone/public
    env:
      - NODE_ENV=production
    secretEnv: ['OPENAI_API_KEY', '_NEXT_PUBLIC_SUPABASE_KEY']

  # 2️⃣ Deployment Step
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy nextjs-app \
          --platform managed \
          --region europe-west4 \
          --allow-unauthenticated \
          --source . \
          --clear-base-image \
          --update-secrets=OPENAI_API_KEY=OPENAI_KEY:latest,_NEXT_PUBLIC_SUPABASE_KEY=NEXT_PUBLIC_SUPABASE_KEY:latest \
          --command="node,build/standalone/server.js"